name: flutter_realtime_exchange
description: Real-time currency quotes with Flutter.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.3
  launcher_name: ^1.0.2
  flutter_lints: ^5.0.0

launcher_name:
  default: "Flutter Realtime Exchange"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/icon.png"
  android: true
  ios: true

flutter_icons:
  ios: true
  android: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - .env
